### ISSUE TITLE
Unable Help Please

### ISSUE THREAD

**Issue by ghost** [IvonLiu/moscrop-secondary-app#2]
Error:Configuration with name 'default' not found. maybe you should try to do it in Android studio. i followed every step from read me and re-configed everything. you have more experience then me @AllanWang so you should try! i am planning to re-make it with Android N and O. Thank You

**Comment by AllanWang** [comment]
Hi @KadwaP . I just checked my email and saw that you are planning to use this as a base for an app for another district. Keep in mind that our app was build specifically to parse google blogs, so if your district isn't doing that, it may not be useful.

As for configurations, this project is quite old so many things are likely outdated. If you are really set on using this as a base, make sure you update all the dependencies (appcompat, etc) or download the older versions so that you can actually import the project.

I will say that it may be easier to build from scratch and take portions of whatever code you need to fulfill your functions.

**Comment by ghost** [comment]
Thank you. I will build from scratch. all i liked was the theme section off the app.

**Comment by AllanWang** [comment]
@KadwaP  have a look at the styles.xml file and the attributes used to create the themes. This method involves presets in that you can only use the themes that are already defined.  It will probably fit your purpose though.
